language: csharp
mono:
  - latest

solution: PCLExt.Nancy.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PCLExt.Nancy.sln
  
script:
  - xbuild /p:Configuration=Release PCLExt.Nancy.sln
  - xbuild /p:Configuration=Debug PCLExt.Nancy.sln

notifications:
  email:
    on_success: always
